name: shotani_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  freezed_annotation: ^0.14.2
  hooks_riverpod: ^0.14.0+4
  logger: ^1.0.0

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2

dependency_overrides:
  freezed: ^0.12.7
  freezed_annotation: ^0.12.0

flutter:
  uses-material-design: true
